### ISSUE TITLE
error when jumping to import

### ISSUE THREAD

**Issue by rr-kalbeck** [alexheyd/atom-jump-to-import#30] opened 2017-10-31 09:50 UTC
holding down cmd over import shows the hand cursor but clicking goes nowhere

Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at _parseWebpackConfig (.atom/packages/jump-to-import/lib/utils/general.js:58:10)
    at .atom/packages/jump-to-import/lib/utils/general.js:187:17
    at Array.forEach (native)
    at Object.extractWebpackAliases (.atom/packages/jump-to-import/lib/utils/general.js:186:26)
    at Object.extractAllAliases (.atom/packages/jump-to-import/lib/utils/general.js:146:33)
    at JumpToImport.setup (.atom/packages/jump-to-import/lib/jump-to-import.js:167:27)
    at JumpToImport.<anonymous> (.atom/packages/jump-to-import/lib/jump-to-import.js:237:12)
    at Generator.next (<anonymous>)
    at step (.atom/packages/jump-to-import/lib/jump-to-import.js:7:273)
    at .atom/packages/jump-to-import/lib/jump-to-import.js:7:443
    at JumpToImport.<anonymous> (.atom/packages/jump-to-import/lib/jump-to-import.js:7:99)
    at Object.<anonymous> (.atom/packages/jump-to-import/lib/jump-to-import.js:59:12)
    at Generator.next (<anonymous>)
    at step (.atom/packages/jump-to-import/lib/jump-to-import.js:7:273)
    at .atom/packages/jump-to-import/lib/jump-to-import.js:7:443
    at Object.callback (.atom/packages/jump-to-import/lib/jump-to-import.js:7:99)
    at t.default._confirmSuggestion (.atom/packages/hyperclick/index.js:1:158042)
    at t.default._onMouseDown (.atom/packages/hyperclick/index.js:1:159072)

**Comment by alexheyd** [comment] 2017-10-31 17:55
Do you have a `webpack.config.js` file with aliases you're expecting to get picked up by the package? If so, could you paste the contents of that file here?

**Comment by alexheyd** [comment] 2017-10-31 19:21
I might have found the culprit for your issue, released in `v3.6.2`
If that doesn't fix things for you, could you also provide some info regarding what string you clicked on, the path you expected it to open and your file structure?

Thanks.

**Comment by alexheyd** [comment] 2017-11-01 18:53
@rr-kalbeck if you could confirm whether this fixed your use case, then I can close this (or provide a fix). Otherwise I'll close this as fixed by tomorrow.

**Comment by rr-kalbeck** [comment] 2017-11-02 07:45
it works now on an import name but not the file reference..

```
import App from './app';
```

ie- works on App but not './app'

file structure here is just 2 files in the same directory index.jsx and app.jsx

**Comment by alexheyd** [comment] 2017-11-02 15:03
Could you enable debug in the package settings and copy/paste the debug log from the console? Or provide info on file structure, file extensions you're trying to open. This would help in reproducing the bug. Also, what other packages do you have installed? Does it work with the keybind?

Edit: I was viewing this on mobile at first, and didn't see the last line regarding the file structure. Someone else recently reported having issues opening `.jsx` files in a straightforward use-case like yours, the culprit was a conflicting package (however I think in his case, neither clicking on the variable nor the path worked). The package in question was `js-hyperclick`: https://github.com/alexheyd/atom-jump-to-import/issues/28#issuecomment-333618164

**Comment by smccarthy** [comment] 2017-11-07 05:15
I'm not sure if my issue is related, but this plugin doesn't work for me either. I see this in the log :
```
Uncaught (in promise) TypeError: Cannot read property 'alias' of undefined
    at /Users/smccarthy/.atom/packages/jump-to-import/lib/utils/atom.js:210:37
    at Array.forEach (native)
    at Object.getWebpackConfigs (/Users/smccarthy/.atom/packages/jump-to-import/lib/utils/atom.js:194:15)
    at JumpToImport.setup (/Users/smccarthy/.atom/packages/jump-to-import/lib/jump-to-import.js:169:34)
    at JumpToImport.<anonymous> (/Users/smccarthy/.atom/packages/jump-to-import/lib/jump-to-import.js:251:12)
    at Generator.next (<anonymous>)
    at step (/Users/smccarthy/.atom/packages/jump-to-import/lib/jump-to-import.js:7:273)
    at /Users/smccarthy/.atom/packages/jump-to-import/lib/jump-to-import.js:7:443
    at JumpToImport.<anonymous> (/Users/smccarthy/.atom/packages/jump-to-import/lib/jump-to-import.js:7:99)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1354:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

My import statement is like :
`import commonPage from '../pages/common';`

Edit: I disabled Webpack Alias's, and it works for me (not with hyperclick yet). I added some console logs to the atom.js file and saw an error about webpack , which led me to disable webpack aliases.

**Comment by alexheyd** [comment] 2017-11-08 17:29
Ah thanks, will look into fixing webpack support.

**Comment by alexheyd** [comment] 2017-11-09 19:04
https://github.com/alexheyd/atom-jump-to-import/commit/4d496192bb48cd80c0b4cd6c33a355300d63bfaa fixes this issue. Released in `v.3.6.5`

**Closed as completed by alexheyd** 2017-11-09 19:04 UTC
