### ISSUE TITLE
Failed to load the jump-to-import package

### ISSUE THREAD

**Issue by yoboseyo** [alexheyd/atom-jump-to-import#27] opened 2017-09-09 19:42 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Windows 10
**Thrown From**: [jump-to-import](https://github.com/alexheyd/atom-jump-to-import) package 3.5.0

### Stack Trace

Failed to load the jump-to-import package

```
At Cannot find module 'symbols-view/lib/tag-generator'

Error: Cannot find module 'symbols-view/lib/tag-generator'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.7/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.7/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.7/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.7/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-jump-to-import/lib/utils/atom.js:5:35)
    at /packages/atom-jump-to-import/lib/utils/atom.js:629:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.7/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.7/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.7/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.7/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-jump-to-import/lib/jump-to-import.js:5:27)
    at /packages/atom-jump-to-import/lib/jump-to-import.js:243:37)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.7/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.7/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.7/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.19.7/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.19.7/resources/app/src/package.js:887:35)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.7/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.19.7/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.19.7/resources/app/src/package-manager.js:565:22)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/src/package-manager.js:479:25
```

### Commands

```
     -9:26.7.0 core:backspace (input.hidden-input)
     -9:26.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.5 
csslint 1.1.5 
jslint 1.5.1 
jump-to-import 3.5.0 
react 0.16.2 
autoclose-html 0.24.0 
autocomplete-js-import 1.4.0 
autocomplete-paths 1.0.2 
autocomplete-paths 1.0.2 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.3 
file-icons 2.1.11 
git-control 0.9.0 
git-plus 7.9.3 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.2.1 
linter-gcc 0.7.1 
linter-ui-default 1.6.8 
open-in-browsers 0.0.30 
platformio-ide-debugger 1.2.4 
platformio-ide-terminal 2.6.0 
tool-bar 1.1.0 
```

**Comment by alexheyd** [comment] 2017-09-13 18:32
Do you have `symbols-view` installed and enabled? https://github.com/atom/symbols-view

**Comment by alexheyd** [comment] 2017-10-10 19:04
Closing as not able to reproduce with `symbols-view` installed and enabled. Please let me know if you're still experiencing issues.

**Closed as completed by alexheyd** 2017-10-10 19:04 UTC

**Comment by bryceh29** [comment] 2018-06-13 17:02
@alexheyd can this be reopened I have the same issue with symbols-view installed and enabled

Cannot find module 'symbols-view/lib/tag-generator'

Stack Trace:

Error: Cannot find module 'symbols-view/lib/tag-generator'

    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\src\module-cache.js:354:58)
    at Module.require (file:///C:/Users/bhill/AppData/Local/atom/app-1.27.2/resources/app.asar/static/index.js:40:43)
    at require (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\src\native-compile-cache.js:66:33)
    at Object.<anonymous> (C:\Users\bhill\.atom\packages\atom-jump-to-import-master\lib\utils\atom.js:7:35)
    at Object.<anonymous> (C:\Users\bhill\.atom\packages\atom-jump-to-import-master\lib\utils\atom.js:722:3)
    at Module.get_Module._compile (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\src\compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///C:/Users/bhill/AppData/Local/atom/app-1.27.2/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\src\native-compile-cache.js:66:33)
    at Object.<anonymous> (C:\Users\bhill\.atom\packages\atom-jump-to-import-master\lib\jump-to-import.js:15:18)
    at Object.<anonymous> (C:\Users\bhill\.atom\packages\atom-jump-to-import-master\lib\jump-to-import.js:333:3)
    at Module.get_Module._compile (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\src\compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///C:/Users/bhill/AppData/Local/atom/app-1.27.2/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\static\<embedded>:96:26)
    at Package.requireMainModule (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\src\package.js:782:33)
    at measure (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\src\package.js:143:22)
    at Package.measure (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\src\package.js:88:25)
    at Package.load (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\src\package.js:129:16)
    at PackageManager.loadAvailablePackage (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\src\package-manager.js:618:16)
    at config.transact (C:\Users\bhill\AppData\Local\atom\app-1.27.2\resources\app\src\package-manager.js:531:20)
`

Jump-to-import is installed:
![image](https://user-images.githubusercontent.com/8051260/41366385-246b0d02-6ef9-11e8-8427-8b118050f644.png)

As well as symbols-view:
![image](https://user-images.githubusercontent.com/8051260/41366407-340f3c4c-6ef9-11e8-84a0-42319a261f1a.png)
