### ISSUE TITLE
It will be nice if it can work with smart-require

### ISSUE THREAD

**Issue by alexisab** [alexheyd/atom-jump-to-import#21] opened 2017-08-04 16:51 UTC
Every things is in the title, it will be cool if it will work with this package : https://github.com/motet-a/smart-require

**Comment by alexheyd** [comment] 2017-08-07 17:51
I can have paths that start with `/` point to the project root. Will be adding in the next release.

**Comment by alexheyd** [comment] 2017-08-07 17:55
Actually I just checked, paths starting with `/` work as intended and point to the project root. Closing.

**Closed as completed by alexheyd** 2017-08-07 17:55 UTC

**Comment by alexisab** [comment] 2017-08-23 14:07
And will it be possible to consider aliases defined, for example, in `webpack.config.js` ? 

I've defined some aliases in my webpack config : 
```
resolve: {
        alias: {
            '~': path.resolve(__dirname, env.NODE_ENV === 'production' ? './server-dist' : './src'),
            'style': path.resolve(__dirname, (env.NODE_ENV === 'production' ? './server-dist' : './src') + '/style'),
        }
    },
```

so in my code I've many `import`s  like `import { ProjectMap } from '~/components/project-map'`.
