### ISSUE TITLE
does not find jsx file extension

### ISSUE THREAD

**Issue by drstonebraker** [alexheyd/atom-jump-to-import#28] opened 2017-09-24 06:07 UTC
When I try to jump to a jsx import, it opens an empty js file instead, unless the pathname is explicitly written as jsx.

**Comment by drstonebraker** [comment] 2017-09-24 06:08
This is true even if I change the ordering of the file extensions in settings

**Comment by alexheyd** [comment] 2017-09-27 07:19
@drstonebraker could you provide the file path and aliases you're using?

**Comment by drstonebraker** [comment] 2017-09-27 07:56
I'm sorry, I don't really understand what you're asking for.  Can you
clarify?

**Comment by alexheyd** [comment] 2017-09-27 08:10
The file you're trying to jump to, what's the path, e.g `import foo from 'path/to/jsx';`? And what "Path Aliases" do you have defined in the package settings?

**Comment by drstonebraker** [comment] 2017-09-27 18:52
For me, the behavior seems consistent across all imports from jsx files.
But one example is:
`import StatusIndicator from './status_indicator'`

There is no './status_indicator.js'.  The extension is '.jsx'.  However,
when I click on `'./status_indicator'` or `StatusIndicator` anywhere on the
page, Atom opens and empty './status_indicator.js' file.  If I add the
explicit `.jsx` extension to `'./status_indicator'` then the correct jsx
file is opened.

I have not used aliases or modified the package settings in any way.

**Comment by alexheyd** [comment] 2017-09-27 19:19
I'm not able to reproduce on my end. If I have 2 files, `foo.jsx` and `bar.jsx` in `project_root/components/`

```javascript
// project_root/components/foo.jsx

import bar from './bar'; // -> opens `project_root/components/bar.jsx`
```

What platform are you on? Could you list your file structure? Thanks.

**Comment by drstonebraker** [comment] 2017-09-27 19:28
I'm on a Mac.  As for my file structure, I have everything inside a
/frontend directory (not using assets pipeline) in a rails project.  I have
webpack bundling my  .js and .jsx files.

**Comment by alexheyd** [comment] 2017-09-27 23:13
So if I'm understanding correctly, you have:
`frontend/status_indicator.jsx` and `frontend/some_file.jsx`

And from `frontend/some_file.jsx` you have:
`import StatusIndicator from './status_indicator';`
and hyperclicking or pressing `SHIFT+CMD+E` on either `StatusIndicator` or `./status_indicator` doesn't open the `.jsx` file, but an empty `.js` file?

Is `/frontend` the root of your project? If it's not the root, do you have any aliases defined in `webpack` by any chance?

**Comment by drstonebraker** [comment] 2017-09-28 05:01
Thank you so much for your help.

Your description is correct with the exception that the components are
nested more deeply within /frontend.  Check out '/some_file.jsx' here:
https://github.com/drstonebraker/plaidchat/blob/develop/frontend/components/chat/sidenav/channel_index_section_list.jsx

My webpack config here:
https://github.com/drstonebraker/plaidchat/blob/develop/webpack.config.js

I'm not using webpack aliases.

If you want, feel free to clone the project and see if you get the same
behavior.

**Comment by alexheyd** [comment] 2017-09-28 18:06
You're very welcome.

Just cloned the project and it works as intended, using mostly default settings (and none of my custom settings affect this particular use case that I'm aware of), so I'm wondering if the issue you're experiencing is due to a package conflict (haven't had any conflicts reported so far). 

Could you post a list of your installed packages? If you run `apm list` in a terminal window, it should output the full list.

When I get a moment I'll push a new release with some debugging included so we can get to the bottom of this. Might not be for a few days though.

**Comment by drstonebraker** [comment] 2017-09-29 06:30
Thanks Alex. I'll note that I do have hyperclick and js-hyperclick
installed.  I tried to disable them to test if that resolves the issue, but
I'm now getting new behavior (and so am unable to test whether the other
packages were causing the old behavior) where I'm not able to jump to any
of my files at all (though I can still jump to imported npm modules like
'react') because the 'clickable' phrases are being split up by any periods
I have in the path.  For example, on an import path like
'../../some_file.js', the first `/` highlights like it's clickable, the
`/some_file` does too, and the `js` does too, but nothing on the periods.
When I click any of these parts of the path, nothing happens.

here are my atom packages.  I have not installed any new ones since the
behavior last change.

[36mBuilt-in Atom Packages [39m (91)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.6
├── one-light-ui@1.10.6
├── one-dark-syntax@1.8.0
├── one-light-syntax@1.8.0
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.6
├── archive-view@0.63.3
├── autocomplete-atom-api@0.10.2
├── autocomplete-css@0.17.2
├── autocomplete-html@0.8.0
├── autocomplete-plus@2.35.7
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.87.3
├── command-palette@0.40.4
├── dalek@0.2.1
├── deprecation-cop@0.56.7
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.4
├── exception-reporting@0.41.4
├── find-and-replace@0.209.5
├── fuzzy-finder@1.5.8
├── github@0.4.0
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.62.3
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.3
├── link@0.31.3
├── markdown-preview@0.159.13
├── metrics@1.2.6
├── notifications@0.69.0
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.251.5
├── snippets@1.1.4
├── spell-check@0.72.1
├── status-bar@1.8.11
├── styleguide@0.49.7
├── symbols-view@0.117.0
├── tabs@0.107.1
├── timecop@0.36.0
├── tree-view@0.217.7
├── update-package-dependencies@0.12.0
├── welcome@0.36.5
├── whitespace@0.37.2
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.4
├── language-coffee-script@0.48.9
├── language-csharp@0.14.2
├── language-css@0.42.4
├── language-gfm@0.90.0
├── language-git@0.19.1
├── language-go@0.44.2
├── language-html@0.47.3
├── language-hyperlink@0.16.2
├── language-java@0.27.2
├── language-javascript@0.127.1
├── language-json@0.19.1
├── language-less@0.33.0
├── language-make@0.22.3
├── language-mustache@0.14.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.42.0
├── language-property-list@0.9.1
├── language-python@0.45.4
├── language-ruby@0.71.3
├── language-ruby-on-rails@0.25.2
├── language-sass@0.61.0
├── language-shellscript@0.25.2
├── language-source@0.9.0
├── language-sql@0.25.8
├── language-text@0.7.3
├── language-todo@0.29.2
├── language-toml@0.18.1
├── language-xml@0.35.2
└── language-yaml@0.30.1

[36mCommunity Packages (23) [39m /Users/drstonebraker/.atom/packages
├── advanced-open-file@0.16.6
├── atom-ternjs@0.18.3
├── autoprefixer@3.7.1
├── busy-signal@1.4.3
├── highlight-selected@0.13.1
├── hyperclick@0.1.5
├── intentions@1.1.2
├── js-hyperclick@1.11.1
├── jump-to-import@3.5.0
├── linter@2.2.0
├── linter-eslint@8.2.1
├── linter-rubocop@2.1.1
├── linter-ui-default@1.6.8
├── minimap@4.29.6
├── minimap-bookmarks@0.4.2
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── pigments@0.40.2
├── platformio-ide-terminal@2.5.4
├── react@0.16.2
├── rspec@0.3.2
└── vim-mode-plus@0.96.2 (disabled)


Sorry to put more work on your plate, but honestly your package is one of
my favorites of all packages when it works.  Bugs or no bugs, I can't
understand why it doesn't have a hundred thousand downloads, unless there
is another package out there that has similar functionality that I couldn't
find.

**Comment by alexheyd** [comment] 2017-09-30 01:34
Thanks for the info, I'll look into this over the weekend.

**Comment by alexheyd** [comment] 2017-10-02 18:12
I was finally able to reproduce the issue after installing `js-hyperclick`. I would suggest using one or the other, as they have a good amount of functionality overlap.

You mentioned that you disabled both `hyperclick` and `js-hyperclick` then started experiencing other issues. The `hyperclick` package is supported and can be left enabled. Be sure to reload Atom after disabling/enabling the packages.

**Comment by drstonebraker** [comment] 2017-10-02 18:36
Thanks!  I try that and let you know if I still experience any issues.

**Comment by alexheyd** [comment] 2017-10-10 17:48
@drstonebraker could you confirm if things are working as expected for you now? If so, will close this ticket, thanks.

**Comment by drstonebraker** [comment] 2017-10-10 18:59
Sorry, yes they are.  Thank you so much!

**Comment by alexheyd** [comment] 2017-10-10 19:03
Cool, np!

**Closed as completed by alexheyd** 2017-10-10 19:03 UTC
